

export const addPharmacy= async()=>
{
    try{

    }
    catch(err)
    {
        console.log("The error is")
    }
}