

export const deletePharmacy = async(req, res, next)=>
{
    try{

    }
    catch(err)
    {

    }
}