
const getData= await()=>
{
    try{

    }
    catch(err)
    {
        console.log(err);
        throw err;
    }
}

constGetAllUnApprovedAppointmenr=()=>
{
    return(

    )
}